name: Deploy API Symfony

on:
  push:
    branches:
      - deploy-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/public_html/api.shogga.com
            git pull origin deploy-api
            composer install --no-dev --optimize-autoloader
            php bin/console cache:clear --env=prod
            php bin/console cache:warmup --env=prod